### ISSUE TITLE
    steps = self.outputs[job_iterator][1][0] KeyError: '34'

### ISSUE THREAD

**Issue by Jasonlin00** [ali1234/comfyui-job-iterator#1]
got an error:
Exception in thread Thread-2 (prompt_worker):
Traceback (most recent call last):
  File "/mnt/disk1/sys/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/mnt/disk1/sys/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/disk1/localroot/ComfyUI/main.py", line 95, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "/mnt/disk1/localroot/ComfyUI/custom_nodes/comfyui-job-iterator/job.py", line 203, in execute
    steps = self.outputs[job_iterator][1][0]
KeyError: '34'

**Comment by ali1234** [comment]
Probably fixed by [d3e49a4](https://github.com/ali1234/comfyui-job-iterator/commit/d3e49a47cfbdffdc4a6ba68cba6f6464b593ac12)

This isn't actually an error in job iterator. One of your other nodes raised an exception and the prompt could not be executed even once, therefore the job iterator was never created.
