### ISSUE TITLE
The funny error. KeyError: '69'

### ISSUE THREAD

**Issue by linnkoln** [ali1234/comfyui-job-iterator#3]
[IP&CN_v0-3_job-itteraitor-test.json](https://github.com/ali1234/comfyui-job-iterator/files/15396872/IP.CN_v0-3_job-itteraitor-test.json)

Prompt executor has been patched by Job Iterator!
total 4
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 295, in map_node_over_list
    _nums = [str(value) for value in input_data_all[input_name]]
                                     ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'number_as_text'

Exception in thread Thread-18 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-job-iterator\job.py", line 203, in execute
    steps = self.outputs[job_iterator][1][0]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '69'

**Comment by ali1234** [comment]
This isn't actually an error in job iterator. One of your other nodes is preventing the workflow from running. However the patch should prevent job iterator from raising a second exception when this happens.
