### ISSUE TITLE
AttributeError: 'PromptExecutor' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by felixsoong0825** [ali1234/comfyui-job-iterator#7]
Prompt executor has been patched by Job Iterator!
JobIterator: 1 / 8
Exception in thread Thread-8 (prompt_worker):
Traceback (most recent call last):
  File "D:\Python\3.11.9\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\Python\3.11.9\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\main.py", line 121, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "D:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-job-iterator\job.py", line 198, in execute
    steps = self.outputs[k][1][0]
            ^^^^^^^^^^^^

**Comment by felixsoong0825** [comment]
sorry I just saw another same issues
